config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :agents
  get 'home/index'
  root 'home#index'
  post 'inbox', :to => 'tickets#inbox', :as => :tickets_index

  resources :tickets do
    member do
      get 'detail'
      post 'reply'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

app/models/agent.rb
class Agent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :tickets, dependent: :destroy


end

# == Schema Information
#
# Table name: agents
#
#  id                     :integer          not null, primary key
#  name                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  validates :subject,
            :from_email,
            :body,
            presence: true



  belongs_to :agent, optional: true
  has_many :ticket_replies, dependent: :destroy

  before_save :set_assigned_at, if: lambda{|ticket| ticket.agent_id.present? }

  def self.create_new_ticket(request_body, subject, from_email, message_body)
    ticket = self.new
    ticket.response_body = request_body
    ticket.subject = subject
    ticket.from_email = from_email
    ticket.body = message_body
    ticket.save!
  end

  def set_assigned_at
    self.assigned_at = Time.now
  end

  def send_and_save_reply(reply_body, new_mail, current_agent)
    if new_mail.deliver!
      ticket_reply = ticket_replies.new
      ticket_reply.body = reply_body
      ticket_reply.from_email = current_agent.email
      self.update(reply_status: true) if ticket_reply.save
    end
  end
end

# == Schema Information
#
# Table name: tickets
#
#  id            :integer          not null, primary key
#  subject       :string
#  from_email    :string
#  body          :text
#  reply_body    :text
#  reply_status  :boolean          default(FALSE)
#  agent_id      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  response_body :text
#  assigned_at   :datetime
#

app/models/ticket_reply.rb
class TicketReply < ApplicationRecord
  belongs_to :ticket_reply, optional: true
end

# == Schema Information
#
# Table name: ticket_replies
#
#  id         :integer          not null, primary key
#  body       :text
#  from_email :string
#  ticket_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_agent!

  def index
    @tickets = current_agent.tickets
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_agent!,  only: [:detail]
  before_action :check_ticket,  only: [:detail, :reply]

  before_action :check_user_ticket,  only: [:detail]


  skip_before_action :verify_authenticity_token

  def inbox
    request_body = request.body.read
    response_body = Mail.read_from_string(request_body)
    subject = response_body.subject
    from_email = response_body.from.first
    message_body = response_body.multipart? ? response_body.text_part.body.to_s : response_body.body.decoded
    Ticket.create_new_ticket(request_body, subject, from_email, message_body)
  end

  def detail
  end

  def reply
    reply_body = params[:reply_body]
    mail = Mail.read_from_string(@ticket.response_body)
    new_mail = mail.reply
    new_mail = mail.reply do
      text_part do
        body reply_body
      end
    end
    @ticket.send_and_save_reply(reply_body, new_mail, current_agent)
    redirect_to home_index_path, notice: "Thanks for your reply."
  end

  private

    def check_ticket
      @ticket = Ticket.find_by_id params[:id]
      unless @ticket.present?
        redirect_to home_index_path, alert: "No ticket present."
      end
    end

    def check_user_ticket
      @ticket = Ticket.find_by_id params[:id]
      unless @ticket.agent_id == current_agent.id
        redirect_to home_index_path, alert: "You are not assigned to this ticket."
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/application/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible notice-alert-div">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </div>
<% end %>

<% if alert.present? %>
  <p class="alert alert-danger notice-alert-div">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= alert %>
  </p>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a class="navbar-brand" href="/">Welcome <%= current_agent.name %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <% if agent_signed_in? %>
      <li class="nav-item right">
        <%= link_to('Logout', destroy_agent_session_path, method: :delete, class: "nav-link") %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a class="navbar-brand" href="#">Welcome <%= current_agent.name %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <% if agent_signed_in? %>
      <li class="nav-item right">
        <%= link_to('Logout', destroy_agent_session_path, method: :delete, class: "nav-link") %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<%= render 'navbar' %>
<br>
<br>
<div class="container">
  <% if @tickets.present? %>
    <table class="table table-striped">
      <caption>My Tickets</caption>
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">From</th>
          <th scope="col">Subject</th>
          <th scope="col">Assigned at</th>
          <th scope="col">Reply Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @tickets.each do |ticket| %>
          <tr>
            <th scope="row"><%= ticket.id %></th>
            <td><%= ticket.from_email %></td>
            <td><%= ticket.subject %></td>
            <td><%= ticket.assigned_at.strftime("%d-%B-%Y | %T%:z") %> </td>
            <td><%= ticket.reply_status ? "Yes" : "No" %></td>
            <td>
              <%= link_to "Reply", detail_ticket_path(ticket)  %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingNinjapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/tickets/detail.html.erb
<%= render 'navbar' %>
<br><br>
<div class="container">
  <h2>Ticket Detail</h2>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Attribute</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Subject</td>
        <td><%= @ticket.subject %></td>
      </tr>
      <tr>
        <td>Email</td>
        <td><%= @ticket.from_email %></td>
      </tr>
      <tr>
        <td>Body</td>
        <td><%= @ticket.body.html_safe %></td>
      </tr>
    </tbody>
  </table>
  <hr>
  <b>Replies</b>
  <ol>
    <% @ticket.ticket_replies.each do |ticket_reply| %>
      <hr>
      <li>
        <%= ticket_reply.body %>
      </li>
    <% end %>
  </ol>
  <br>
  <br>
  <b>New Reply</b>
  <%= form_tag reply_ticket_path, :remote  => true, :method => :post  do -%>
    <%= text_area_tag 'reply_body', nil, rows: 5, cols: 135 %>
    <button name="button" type="submit">Reply</button>
  <% end %>
</div>